name = "create focused war"
author = "oygurd"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45f8ac25947218bd9fd912631c62081a629762425da391e4e5f95439821cfeb5"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
