
#一些常规的配置
["常规"]
	#是否允许EntityTicker作用于玩家，由于可能导致问题所以默认false
	allow_entity_ticker_on_player = false
	#是否允许弹射物在命中方块后依然通过ProjectileTickModifierHook遍历全词条，默认false
	allow_projectile_tick_inground = false
	#是否允许一般的工具在被合成时拥有UUID，默认否
	allow_common_tool_having_uuid = false
	#是否允许一般的可堆叠工具在被合成时拥有UUID，默认否（仅在allow_common_tool_having_uuid=true时有效）
	allow_stackable_tool_having_uuid = false
	#是否允许范围伤害波及其它玩家，默认否。
	allow_aoe_attack_player = false

