
#***注意！
#***Notice
#这些配置并不会同步修改语言文件中的描述，当你修改了某个工具/工具属性的性质后如果想要更改描述则需要手动覆盖语言文件！
#This configure won't affect language display. When a certain modifier or tool is configured, please manually replace the description of the relating language contents.
#Worldgen
#世界生成
[worldgen]
	#Allows Bismuthinite generation, true by default.
	#允许辉铋矿生成，默认是。
	allow_bismuthinite = true
	#Allows Stibnite generation, true by default.
	#允许辉锑矿生成，默认是。
	allow_stibnite = true
	#Allows Unstable Stibnite generation when mining Stibnite, true by default.
	#允许挖掘辉锑矿时使周围的辉锑矿在稳定和不稳定之间切换，默认是。
	allow_stibnite_unstable = true
	#Allows Iridium generation, true by default.
	#允许贫铱矿生成，默认是。
	allow_iridium = true

#Modifiers behaviour
#词条性质
[modifier_behaviour]
	#Shaping
	#塑性
	#Max upgrade slot bonus for Shaping modifier, 3 by default.
	#最大加槽，默认3。
	#Range: > 1
	shaping_max_slot = 3
	#How many durability loss is needed for Shaping modifier to gain 1 slot, 500 by default.
	#磨损多少耐久才加1升级槽，默认500。
	#Range: > 1
	shaping_damages_each_slot = 500
	#Proto Refining
	#原体精炼
	#Bonus enchantment level each trait level for Proto Refining, 3 by default.
	#每级最大时运增益，默认3。
	#Range: > 0
	proto_refining_bonus = 3
	#How many times needed for Proto Refining to gain bonus, 5 by default.
	#挖多少次增加1级时运，默认5。
	#Range: > 1
	proto_refining_requirement = 5
	#Radiation Burning and Radioactive Armor
	#镭光合金相关
	#Max bonus for Radiation Burning and Radioactive Armor, 0.75 by default.
	#最大增益，默认0.75。
	#Range: 0.0 ~ 1.0
	irradium_max_bonus = 0.75
	#Radiation amount for Radiation Burning and Radioactive Armor each trait level, 1.0 Sv by default.
	#辐射施加，默认1.0Sv。
	#Range: 0.0 ~ 1.7976931348623157E308
	irradium_radiation_inflict = 1.0
	#Bonus for Radiation Burning and Radioactive Armor each Sv, 0.05 by default.
	#每Sv辐射造成的增幅，默认0.05。
	#Range: 0.0 ~ 1.0
	irradium_bonus_per_sv = 0.05
	#Fragile
	#脆性
	#Chance for extra durability draw for Fragile Modifier, 0.1 by default.
	#脆性额外消耗耐久的概率，默认0.1。
	#Range: 0.0 ~ 1.0
	fragile_chance = 0.1
	#Extra durability cost for Fragile, 1 by default.
	#额外消耗的耐久，默认1。
	#Range: > 0
	fragile_cost = 1
	#Reactive Explosive Armor
	#Allows Reactive Explosive Armor Modifier to block explosion and fire damage, true by default.
	reactive_explosive_armor_immunity = true
	#Damage Reduction for Reactive Explosive Armor, 0.25 by default.
	#Range: 0.0 ~ 1.0
	reactive_explosive_armor_reduction = 0.25
	#Nutritive Slime
	#营养黏液
	#Overslime consumption for each food level, 20 by default.
	#每点饱食度需要的黏液覆层消耗量，默认20。
	#Range: > 0
	nutritive_slime_cost = 20
	#Food level to add each trait level, 1 by default.
	#每级一次性加的饱食度，默认1。
	#Range: > 0
	nutritive_slime_recover = 1
	#Return to Slime
	#万物归于黏液
	#Overslime recover chance for Return to Slime each trait level, 20% by default.
	#恢复黏液覆层的概率，默认20%
	#Range: 0.0 ~ 1.0
	return_to_slime_chance = 0.2
	#Annihilation
	#湮灭
	#Explosion damage multiplier for Annihilation Modifier, 5 by default.
	#湮灭词条造成的爆炸伤害倍率，默认5倍。
	#Range: 0.0 ~ 2.147483647E9
	annihilation_attack_multiplier = 5.0
	#Explosion damage multiplier that deals to attacker, 2.5 by default.
	#湮灭词条对自己造成的爆炸伤害倍率，默认2.5倍
	#Range: 0.0 ~ 2.147483647E9
	annihilation_attack_self_multiplier = 2.5
	#Disintegrate
	#解离
	#Bonus each block mined (%), 20(%) by default
	#挖掘每个方块带来的加成（单位为%），默认20%。注：耐久惩罚是加成的一半。
	#Range: > 0
	disintegrate_each_bonus = 20
	#Max bonus, 2000% by default.
	#最大加成（单位为%），默认2000%。
	#Range: > 0
	disintegrate_max_bonus = 2000
	#Clear bonus after ticks of stopping, 5s by default.
	#停止挖掘多久后清除加成，默认5秒。
	#Range: > 0
	disintegrate_each_decrease = 5
	#Void Dodging
	#虚无闪避
	#Chance for dodging arrow each level, 0.25 by default.
	#每级闪避箭矢的概率，默认0.25。
	#Range: 0.0 ~ 1.0
	void_dodging_chance = 0.25
	#Flux Infuse
	#通量注入
	#通量注入抵消耐久消耗需要的能量，默认500FE
	#FE required for each durability loss, 500FE by default
	#Range: > 0
	flux_infuse_consumption = 500
	#Flux Slash
	#通量赋能-近战
	#通量斩击的基础消耗（通量伤害消耗采用此值，剑气消耗为此值的2倍），默认250FE
	#Basic consumption for Flux Slash, 250FE by default.
	#Range: > 0
	flux_slash_consumption = 250
	#通量斩击的额外通量伤害，默认4
	#Additional Flux damage for Flux Slash, 4 by default.
	#Range: 0.0 ~ 3.4028234663852886E38
	flux_slash_flux_damage = 4.0
	#通量斩击的剑气基础伤害，默认4
	#Base damage for the slash from Flux Slash, 4 by default.
	#Range: 0.0 ~ 3.4028234663852886E38
	flux_slash_base_slash_damage = 4.0
	#通量斩击的剑气受锋利词条的伤害加成，默认0.5每级
	#Sharpness modifier bonus damage for Slash from Flux Slash, 0.5 by default.
	#Range: 0.0 ~ 3.4028234663852886E38
	flux_slash_damage_per_sharpness = 0.5
	#通量斩击的剑气继承自工具伤害的伤害比例，默认0x
	#Damage bonus from tool's attack damage, 0x by default.
	#Range: 0.0 ~ 3.4028234663852886E38
	flux_slash_damage_from_attack_damage = 0.0
	#通量斩击的挖掘加速（注能模式下为此值2倍），默认100%
	#Mining boost for Flux Slash, 100% by default.
	#Range: 0.0 ~ 3.4028234663852886E38
	flux_slash_dig_speed_bonus = 1.0
	#Flux Arrow
	#通量赋能-远程
	#通量箭矢的基础消耗（箭矢增伤消耗采用此值，产生箭矢消耗为此值的2倍，箭矢爆炸为此值的3倍，复制药水箭消耗为此值的4倍），默认250FE
	#Basic consumption for Flux Arrow, 250FE by default.
	#Range: > 0
	flux_arrow_consumption = 250
	#通量箭矢的爆炸伤害，默认5
	#Arrow explosion damage for Flux Arrow, 5 by default.
	#Range: 0.0 ~ 3.4028234663852886E38
	flux_arrow_explosion_damage = 5.0
	#通量箭矢爆炸受到箭矢伤害的增幅，默认0x
	#Additional damage for the arrow explosion boosted by arrow damage from Flux Arrow, 0x by default.
	#Range: 0.0 ~ 3.4028234663852886E38
	flux_arrow_explosion_damage_from_arrow_damage = 0.0
	#Flux Armor
	#通量赋能-护甲
	#通量护甲的基础消耗（减伤消耗采用此值，闪避消耗为此值的10倍），默认2000FE
	#Basic consumption for Flux Armor, 2000FE by default.
	#Range: > 0
	flux_armor_consumption = 2000
	#通量护甲的伤害减免，默认0.2x
	#Damage Reduction for Flux Armor, 0.2x by default.
	#Range: 0.0 ~ 1.0
	flux_armor_damage_reduction = 0.2
	#通量护甲的闪避率，默认0.05
	#Dodge rate for Flux Armor, 0.05 by default.
	#Range: 0.0 ~ 1.0
	flux_armor_dodge_rate = 0.05
	#Generator Modules
	#能量模块类强化
	#Basic FE/t for each level of Combustion Generator Module, 200 by default
	#燃烧室能量模块的基础每tick产能，默认200FE/t。
	#Range: > 0
	combustion_generator_generation = 200
	#Energy per burning time, affects the total FE generated by fuel item. 10 by default, in this case a single coal can produce 16.00 kFE.
	#燃料每tick燃烧时间带来的总产能，默认10FE。注：烧炼一个物品需要200 ticks，一个煤炭能烧8个物品也就是1600 ticks，这代表默认配置下一个煤炭能带来16.0kFE的总产能。
	#Range: > 0
	combustion_generator_total_factor = 10
	#Basic FE/t for each level of Overslime Generator Module, 250 by default
	#凝胶电化学能量模块的基础每tick产出，默认250FE/t
	#Range: > 0
	overslime_generator_generation = 250
	#Energy per overslime, 1000 by default.
	#每点黏液产生的能量，默认1kFE。
	#Range: > 0
	overslime_generator_total_factor = 1000
	#Basic FE/t for each level of Piezoelectric Effect modifier, 100 by default
	#压电效应的基础每tick产能，默认100FE/t。
	#Range: > 0
	piezoelectric_effect_generation = 100
	#Energy per damage each level, 10 by default.
	#每级每点伤害产生的能量，默认10FE。
	#Range: > 0
	piezoelectric_effect_generation_per_damage = 10
	#Basic FE/t for each level of Electric Food modifier, 100 by default
	#充电饱的基础每tick消耗，默认100FE/t。
	#Range: > 0
	electric_food_consumption = 100
	#Energy per food level, 25kFE by default.
	#充电饱恢复1饱食度需要的能量，默认25kFE。
	#Range: > 0
	electric_food_total_consumption = 25000
	#Bonus for Transition Catalyst each trait level, 25% by default.
	#过渡金属催化剂的增幅效果，默认25%。
	#Range: 0.0 ~ 2.147483647E9
	transition_catalyst_bonus = 0.25
	#Bonus for Platinoid Catalyst each trait level, 25% by default.
	#铂族催化剂的增幅效果，默认25%。
	#Range: 0.0 ~ 2.147483647E9
	platinoid_catalyst_bonus = 0.25
	#Basic FE/t for each level of Smeltery Generator modifier, 300 by default
	#冶炼炉能量模块基础的每tick能量产出。默认300 FE/t。
	#Range: > 0
	smeltery_generator_generation = 300
	#Energy per burning time, 10000 by default.
	#每tick燃烧时长带来的总能量产出。默认10kFE。
	#Range: > 0
	smeltery_generator_generation_for_time = 10000
	#Power multiplier for fuel temp, 0.001 by default , meaning that a 2000℃ fuel makes FE/t times 2.
	#燃料温度对产能速率的影响。默认0.001，意味着2000℃的燃料会带来2倍的产能速度。
	#Range: 0.0 ~ 2.147483647E9
	smeltery_generator_temperature_multiplier = 0.001
	#Basic FE/t for each level of Compressed Air Generator modifier, 200 by default
	#气动能量模块基础的每tick能量产出，默认50FE/t。注：最终产能会乘以工具压力。
	#Range: > 0
	compressed_air_generator_generation = 50

#Effects
#状态效果行为
[mob_effect]
	#Damage multiplier for Tetanus, 1.2 by default.
	#破伤风效果导致的受击伤害倍率。默认1.2。
	#Range: 0.0 ~ 2.147483647E9
	tetanus_damage_boost = 1.2
	#Permanent health decrease for Proto poison, 25% by default.
	#原毒效果的永久生命上限减少，默认25%。
	#Range: 0.0 ~ 2.147483647E9
	proto_poison_health_decrease = 0.25
	#Regeneration reduction for Proto Poison each level, 20% by default
	#原毒效果的每级生命再生减少，默认20%。
	#Range: 0.0 ~ 2.147483647E9
	proto_poison_regen_decrease = 0.2
	#Damage for Plague each level, 2 by default.
	#疫毒效果的伤害，默认2。
	#Range: 0.0 ~ 2.147483647E9
	plague_health_decrease = 2.0
	#Regeneration reduction for Plague each level, 50% by default
	#疫毒效果的每级生命再生减少，默认50%。
	#Range: 0.0 ~ 2.147483647E9
	plague_regen_decrease = 0.5

#Tool Behaviour
#工具行为
[tool_behaviour]
	#Matter Manipulator behaviour
	#物质操纵器
	#Base mining speed multiplier of Matter Manipulator, 1.0 by default.
	#物质操纵器的定性挖掘效率倍率，默认1.0x。
	#Range: 0.0 ~ 2.147483647E9
	matter_manipulator_base_multiplier = 1.0
	#Base mining speed multiplier of Matter Manipulator when is conducting AOE mining, 0.5 by default.
	#物质操纵器进行范围挖掘时的定性挖掘效率倍率，默认0.5x。
	#Range: 0.0 ~ 2.147483647E9
	matter_manipulator_aoe_base_multiplier = 0.5
	#Mining fluid bonus multiplier of Matter Manipulator , 0.5 by default , meaning that each 200 °C adds 1 mining speed.
	#流体温度对物质操纵器挖掘速度的定量效率增幅。默认0.5x，意味着挖掘液每200℃增加1挖掘速度。
	#Range: 0.0 ~ 2.147483647E9
	matter_manipulator_fluid_bonus_multiplier = 0.5
	#Allows Matter Manipulator to gain enchantment boost from fluids in mining mode (e.g. Gain silk touch from molten emerald). true by default.
	#允许挖掘模式下的物质操纵器从流体效果中获得附魔等级（比如熔融钻石的时运III），默认true。
	matter_manipulator_fluid_enchanting = true
	#Base mining range for Matter Manipulator, 16.0 by default.
	#物质操纵器的基础挖掘距离，默认16.0格。
	#Range: 0.0 ~ 64.0
	matter_manipulator_base_range = 16.0
	#Capacity factor for Matter Manipulator, 10.0 by default.
	#物质操纵器的流体容量倍率，默认10.0x。
	#Range: 0.0 ~ 2.147483647E9
	matter_manipulator_base_capacity_factor = 10.0
	#Base fluid efficiency for Matter Manipulator, 1.0 by default.
	#物质操纵器的基础流体效率，默认0.0。
	#Range: 0.0 ~ 2.147483647E9
	matter_manipulator_base_fluid_efficiency = 0.0
	#Cancel the movement punishment when using Matter Manipulator,true by default.
	#取消物质操纵器使用时的移速惩罚，默认是。
	matter_manipulator_cancel_slowdown = true
	#Ionized Cannon behaviour
	#等离子射线炮
	#The multiplier of fluid consumption of Ionized Cannon, 1.0 by default.
	#等离子射线炮的定性流体消耗倍率，默认1.0x。
	#Range: 0.0 ~ 2.147483647E9
	ionized_cannon_fluid_factor = 1.0
	#Damage multiplier for Ionized Cannon when using correct fluids, 4.0 by default.
	#当有合适流体时等离子射线炮的伤害倍率，默认4.0x。
	#Range: 1.0 ~ 2.147483647E9
	ionized_cannon_damage_bonus = 4.0
	#Base fluid efficiency for Ionized Cannon, 0.0 by default.
	#等离子射线炮的基础流体效率，默认0.0。
	#Range: 0.0 ~ 2.147483647E9
	ionized_cannon_base_fluid_efficiency = 0.0
	#Base explosion scale efficiency for Ionized Cannon, 1.0 by default.
	#等离子射线炮的基础效果范围，默认1.0。
	#Range: 0.0 ~ 2.147483647E9
	ionized_cannon_base_scale = 1.0
	#Base attack range for Ionized Cannon, 12.0 by default.
	#等离子射线炮的基础攻击距离，默认12.0格。
	#Range: 0.0 ~ 2.147483647E9
	ionized_cannon_base_range = 12.0
	#Base duration for Ionized Cannon to charge, 40 ticks by default.
	#等离子射线炮的基础蓄力时间，默认40 ticks。最终蓄力时间会除以攻速。
	#Range: > 0
	ionized_cannon_base_duration = 40
	#Allow Ionized Cannon to gain pierce level form impaling modifier, true by default.
	#允许等离子射线炮根据穿透词条的等级增加射线穿透数量，默认是。
	ionize_cannon_pierce_from_impaling = true
	#Electron Tuner behaviour
	#环流电子调谐剑
	#The adjustable range of attack damage for Electron Tuner, 1.5 by default, meaning that the damage can be adjusted within the range of ±0.75 .Note that adjusting this without adjusting electron_tuner_attack_speed_range will greatly affect balance.
	#环流电子调谐剑的伤害调节范围。默认1.5，意味着滑动调节滑块最大能对伤害产生 1/1.75 x ~ 1.75 x 的变化。仅调节此项会极大影响平衡，请考虑和攻速范围一同调整。
	#Range: 0.0 ~ 2.147483647E9
	electron_tuner_damage_range = 1.5
	#The adjustable range of attack damage for Electron Tuner, 1.0 by default, meaning that the damage can be adjusted within the range of ±0.5 .Note that adjusting this without adjusting electron_tuner_damage_range will greatly affect balance.
	#环流电子调谐剑的攻击速度调节范围。默认1.0，意味着滑动调节滑块最大能对攻速产生 1/1.5 x ~ 1.5 x 的变化。仅调节此项会极大影响平衡，请考虑和伤害范围一同调整。
	#Range: 0.0 ~ 2.147483647E9
	electron_tuner_attack_speed_range = 1.0
	#Allow Electron Tuner to perform special attack , true by default.
	#允许环流电子调谐剑造成特殊攻击（比如剑形态的弧光），默认true。
	electron_tuner_special = true
	#The basic energy consumption when attacking for Electron Tuner, 250 by default.
	#环流电子调谐剑攻击的能耗，默认250FE。
	#Range: > 0
	electron_tuner_consumption = 250

#Utilities
#实用设备
[utilities]
	#Transfer speed for Cinderslime Faucet, 1000mB/t by default.
	#余烬黏液浇筑口的传输速率，默认1000mB/t。
	#Range: 1 ~ 200000000
	cinderslime_faucet_speed = 1000
	#Transfer speed for Iridium Faucet, 2000000000mB/t by default.
	#铱浇筑口的传输速率，默认2000000000mB/t。
	#Range: 1 ~ 2000000000
	iridium_faucet_speed = 2000000000
	#Cinderslime Casting Speed multiplier with low temp recipes,5x by default.
	#余烬黏液铸件台处理快速配方时的速度倍率，默认5x。
	#Range: 0.0 ~ 2.147483647E9
	cinderslime_casting_increase = 5.0
	#Cinderslime Casting Speed multiplier with high temp recipes,0.5x by default.
	#余烬黏液铸件台处理慢速配方时的速度倍率，默认0.5x。
	#Range: 0.0 ~ 2.147483647E9
	cinderslime_casting_decrease = 0.5
	#Recipe time separator for Cinderslime Table containers,100 ticks by default.
	#余烬黏液铸件台的快慢速分界线，默认100刻(5秒)。
	#Range: > 1
	cinderslime_table_separation = 100
	#Recipe time separator for Cinderslime Basin containers,180 ticks by default.
	#余烬黏液铸件台的快慢速分界线，默认180刻(9秒)。
	#Range: > 1
	cinderslime_basin_separation = 180
	#Iridium Casting speed modifier, 3x by default.
	#铱铸件台的速度倍率，默认3x。
	#Range: 0.0 ~ 2.147483647E9
	iridium_casting_speed = 3.0

#Mekanism Interaction
#通用机械交互
[mekanism_interaction]
	#Enables fusion reactor exploding when throwing iron ingots into it. true by default.
	#让你能够通过向朋友的聚变反应堆丢入铁锭/块/粒/砧来增进彼此的感情，默认是。
	allow_neutronite_crafting = true

